/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ICreateOrderReqDto } from '../../models/i-create-order-req-dto';
import { ICreateOrderResDto } from '../../models/i-create-order-res-dto';

export interface OrderControllerCreateOrder$Params {
      body: ICreateOrderReqDto
}

export function orderControllerCreateOrder(http: HttpClient, rootUrl: string, params: OrderControllerCreateOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<ICreateOrderResDto>> {
  const rb = new RequestBuilder(rootUrl, orderControllerCreateOrder.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ICreateOrderResDto>;
    })
  );
}

orderControllerCreateOrder.PATH = '/api/v1/order';
