/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IECallbackFormStatus } from '../models/ie-callback-form-status';
export interface ICallbackFormSchema {

  /**
   * document _id in uuid format
   */
  '_id': string;
  createdAt: string;

  /**
   * Имя клиента, оставившего заявку
   */
  name: string;

  /**
   * Номер телефона для обратной связи
   */
  phone: string;
  status: IECallbackFormStatus;
  updatedAt: string;
  version: number;
}
