/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ICoordinatesSchema {

  /**
   * Широта
   */
  latitude: number;

  /**
   * Долгота
   */
  longitude: number;
}
