/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IRouteSummaryDto } from '../models/i-route-summary-dto';
export interface ICreateTripReqDto {

  /**
   * Количество детских кресел
   */
  childCarSeatCount: number;

  /**
   * Дата и время подачи автомобиля
   */
  dateTime: string;

  /**
   * Адрес отправления
   */
  departureAddress: string;

  /**
   * Адрес прибытия
   */
  destinationAddress: string;

  /**
   * Имя пассажира
   */
  fullName: string;

  /**
   * Есть ли животные в поездке
   */
  isPetsOnTrip: boolean;

  /**
   * Номер телефона
   */
  mobileNumber: number;

  /**
   * Количество пассажиров
   */
  passengerCount: number;

  /**
   * Стоимость поездки (руб)
   */
  price: number;

  /**
   * Название тарифа
   */
  route: IRouteSummaryDto;

  /**
   * Название тарифа (economy, standard и др.)
   */
  tariff: string;
}
