/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ICreateCallbackFormReqDto {

  /**
   * Имя клиента
   */
  name: string;

  /**
   * Номер телефона клиента
   */
  phone: string;
}
