/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IRouteTripSchema } from '../models/i-route-trip-schema';
export interface ICreateTripResDto {

  /**
   * document _id in uuid format
   */
  '_id': string;

  /**
   * Количество детских кресел
   */
  childCarSeatCount: number;
  createdAt: string;

  /**
   * Дата и время подачи автомобиля
   */
  dateTime: string;

  /**
   * Адрес места отправления
   */
  departureAddress: string;

  /**
   * Адрес места прибытия
   */
  destinationAddress: string;

  /**
   * Имя пассажира
   */
  fullName: string;

  /**
   * Есть ли животные в поездке
   */
  isPetsOnTrip: boolean;

  /**
   * Контактный номер телефона
   */
  mobileNumber: number;

  /**
   * Количество пассажиров
   */
  passengerCount: number;

  /**
   * Стоимость поездки (руб)
   */
  price: number;

  /**
   * Название тарифа
   */
  route: IRouteTripSchema;

  /**
   * Название тарифа (economy, standard и др.)
   */
  tariff: string;
  updatedAt: string;
  version: number;
}
