/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ICreateReviewReqDto {

  /**
   * Тип автомобиля
   */
  carType?: string;

  /**
   * Дата публикации
   */
  date?: string;

  /**
   * Дата публикации
   */
  email?: string;

  /**
   * Имя автора
   */
  name: string;

  /**
   * Дата публикации
   */
  phone?: string;

  /**
   * Список фото
   */
  photos?: Array<string>;

  /**
   * Оценка (1-5)
   */
  rating: number;

  /**
   * ID маршрута
   */
  route: string;

  /**
   * Текст отзыва
   */
  text: string;

  /**
   * Дата публикации
   */
  userId?: string;
}
