/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IFaqSource } from '../models/i-faq-source';
export interface ICreateFaqReqDto {

  /**
   * Ответ
   */
  answer: string;

  /**
   * Категория
   */
  category?: string;

  /**
   * Развернуть по умолчанию
   */
  isExpanded?: string;

  /**
   * Порядок сортировки
   */
  order?: number;

  /**
   * Вопрос
   */
  question: string;
  source?: IFaqSource;

  /**
   * Теги
   */
  tags?: Array<string>;
}
