/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IReviewReplySchema } from '../models/i-review-reply-schema';
export interface ICreateReviewResDto {

  /**
   * document _id in uuid format
   */
  '_id': string;

  /**
   * Тип автомобиля (если применимо)
   */
  carType?: string;
  createdAt: string;

  /**
   * Дата отзыва
   */
  date: string;

  /**
   * Идентификатор маршрута
   */
  email: string;

  /**
   * Имя автора отзыва
   */
  name: string;

  /**
   * Идентификатор маршрута
   */
  phone: string;

  /**
   * Фото пользователя
   */
  photos?: Array<string>;

  /**
   * Оценка от 1 до 5
   */
  rating: number;

  /**
   * Ответ на отзыв
   */
  reply?: IReviewReplySchema;

  /**
   * Идентификатор маршрута
   */
  route: string;

  /**
   * Текст отзыва
   */
  text: string;
  updatedAt: string;

  /**
   * Идентификатор маршрута
   */
  userId: string;
  version: number;
}
