/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Источник записи
 */
export enum IFaqSource {
  Manual = 'manual',
  Support = 'support',
  Ai = 'ai'
}
