/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IFindReviewsItemDto } from '../models/i-find-reviews-item-dto';
export interface IFindReviewsResDto {

  /**
   * Список отзывов
   */
  data: Array<IFindReviewsItemDto>;
}
