/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IFindReviewsReqDto {

  /**
   * Максимальный рейтинг
   */
  maxRating?: number;

  /**
   * Минимальный рейтинг
   */
  minRating?: number;

  /**
   * ID маршрута для фильтрации
   */
  route?: string;
}
