/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ICoordinatesSchema } from '../models/i-coordinates-schema';
import { ILocationSlugsSchema } from '../models/i-location-slugs-schema';
export interface IFindLocationsItemDto {

  /**
   * document _id in uuid format
   */
  '_id': string;

  /**
   * Синонимы для поиска (на любом языке)
   */
  aliases: Array<string>;

  /**
   * Координаты по WGS84
   */
  coordinates: ICoordinatesSchema;
  createdAt: string;

  /**
   * Name для отображения
   */
  name: string;

  /**
   * Локализованные slug для URL
   */
  names: ILocationSlugsSchema;

  /**
   * Регион или область
   */
  region: string;

  /**
   * Slug для URL и поиска
   */
  slug: string;

  /**
   * Тип локации
   */
  type: string;
  updatedAt: string;
  version: number;
}
