/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IFaqSource } from '../models/i-faq-source';
export interface IFindFaqItemDto {

  /**
   * document _id in uuid format
   */
  '_id': string;

  /**
   * Ответ
   */
  answer: string;

  /**
   * Категория
   */
  category?: string;
  createdAt: string;

  /**
   * Развернут по умолчанию
   */
  isExpanded?: string;

  /**
   * Порядок сортировки (ASC)
   */
  order?: number;

  /**
   * Порядок сортировки (ASC)
   */
  priority?: string;

  /**
   * Вопрос
   */
  question: string;
  source?: IFaqSource;

  /**
   * Теги
   */
  tags?: Array<string>;
  updatedAt: string;
  version: number;
}
