/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ICallbackFormSchema } from '../models/i-callback-form-schema';
import { IPaginationMetaDto } from '../models/i-pagination-meta-dto';
export interface IFindCallbackFormsResDto {

  /**
   * Список полученных форм обратной связи
   */
  data: Array<ICallbackFormSchema>;

  /**
   * Пагинация
   */
  meta: IPaginationMetaDto;
}
