/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IFindTariffsItemDto } from '../models/i-find-tariffs-item-dto';
export interface IFindTariffsResDto {

  /**
   * Список найденных тарифов
   */
  data: Array<IFindTariffsItemDto>;
}
