/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IFaqSource } from '../models/i-faq-source';
export interface IFindFaqReqDto {

  /**
   * Категория
   */
  category?: string;

  /**
   * Filters to apply. Example: `filters[status]=active&filters[age][gte]=18`
   */
  filters?: {
};

  /**
   * Number of items per page. Max 100.
   */
  limit?: number;

  /**
   * Page number for pagination.
   */
  page?: number;

  /**
   * Search term for a full-text search across predefined fields.
   */
  search?: string;

  /**
   * Field to sort by.
   */
  sortBy?: string;

  /**
   * Sort order.
   */
  sortOrder?: 'asc' | 'desc';
  source?: IFaqSource;

  /**
   * Тег для фильтрации
   */
  tag?: string;
}
