/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IFindFaqItemDto } from '../models/i-find-faq-item-dto';
import { IPagedResponseDto } from '../models/i-paged-response-dto';
export interface IFindFaqResDto {

  /**
   * Список FAQ
   */
  data: Array<IFindFaqItemDto>;
  meta?: IPagedResponseDto;
}
