/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IFindTripsItemDto } from '../models/i-find-trips-item-dto';
export interface IFindTripsResDto {

  /**
   * Список найденных поездок
   */
  data: Array<IFindTripsItemDto>;
}
