/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IFindLocationsItemDto } from '../models/i-find-locations-item-dto';
export interface IFindLocationsResDto {

  /**
   * Список найденных локаций
   */
  data: Array<IFindLocationsItemDto>;
}
