/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ILocationSlugsSchema {

  /**
   * Название на английском
   */
  en: string;

  /**
   * Название на русском
   */
  ru: string;
}
