/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IPaginationMetaDto {

  /**
   * The current page number.
   */
  currentPage: number;

  /**
   * Number of items requested per page.
   */
  itemsPerPage: number;

  /**
   * Total number of items available.
   */
  totalItems: number;

  /**
   * Total number of pages.
   */
  totalPages: number;
}
