/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IPaginationMetaDto } from '../models/i-pagination-meta-dto';
export interface IPagedResponseDto {
  data: Array<Array<any>>;
  meta: IPaginationMetaDto;
}
