/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IRouteSummaryDto } from '../models/i-route-summary-dto';
import { ITariffPriceItemDto } from '../models/i-tariff-price-item-dto';
export interface IQuoteWithPricesDto {

  /**
   * Итоговый маршрут
   */
  route: IRouteSummaryDto;

  /**
   * Цены по тарифам
   */
  tariffs: Array<ITariffPriceItemDto>;
}
