/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IReviewReplySchema {

  /**
   * Дата ответа
   */
  date?: string;

  /**
   * Имя автора ответа
   */
  name: string;

  /**
   * Текст ответа
   */
  text: string;
}
