/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IRouteTripSchema {

  /**
   * Дистанция, км
   */
  distanceKm: number;

  /**
   * Продолжительность, минуты
   */
  durationMinutes: number;

  /**
   * document _id in uuid format
   */
  locationFromId: string;

  /**
   * document _id in uuid format
   */
  locationToId: string;
}
