/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ILocationSchema } from '../models/i-location-schema';
export interface IRouteSummaryDto {

  /**
   * Дистанция, км
   */
  distanceKm: number;

  /**
   * Продолжительность, минуты
   */
  durationMinutes: number;
  locationFrom: ILocationSchema;
  locationTo: ILocationSchema;
}
