/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ITariffSchema } from '../models/i-tariff-schema';
export interface ITariffPriceItemDto {

  /**
   * Стоимость маршрута по тарифу
   */
  price: number;

  /**
   * Tariff entity
   */
  tariff: ITariffSchema;
}
