/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ITariffSchema {

  /**
   * document _id in uuid format
   */
  '_id': string;

  /**
   * string
   */
  carTypes: Array<string>;
  createdAt: string;

  /**
   * Desc
   */
  description: string;

  /**
   * string
   */
  features: Array<string>;

  /**
   * pic
   */
  image: string;

  /**
   * is active
   */
  isActive: boolean;

  /**
   * Множитель тарифа (руб/км)
   */
  multiplier: number;

  /**
   * Название тарифа (economy, standard, business и т.д.)
   */
  name: string;

  /**
   * string
   */
  options: Array<string>;

  /**
   * order
   */
  order: number;

  /**
   * pic
   */
  seats: number;
  updatedAt: string;
  version: number;
}
