/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ICallbackFormSchema } from '../../models/i-callback-form-schema';
import { ICreateCallbackFormReqDto } from '../../models/i-create-callback-form-req-dto';

export interface CallbackFormsApiControllerCreate$Params {
      body: ICreateCallbackFormReqDto
}

export function callbackFormsApiControllerCreate(http: HttpClient, rootUrl: string, params: CallbackFormsApiControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ICallbackFormSchema>> {
  const rb = new RequestBuilder(rootUrl, callbackFormsApiControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ICallbackFormSchema>;
    })
  );
}

callbackFormsApiControllerCreate.PATH = '/api/v1/callback-forms';
