/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IUpdateFaqReqDto } from '../../models/i-update-faq-req-dto';
import { IUpdateFaqResDto } from '../../models/i-update-faq-res-dto';

export interface FaqApiControllerUpdate$Params {
      body: IUpdateFaqReqDto
}

export function faqApiControllerUpdate(http: HttpClient, rootUrl: string, params: FaqApiControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<IUpdateFaqResDto>> {
  const rb = new RequestBuilder(rootUrl, faqApiControllerUpdate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IUpdateFaqResDto>;
    })
  );
}

faqApiControllerUpdate.PATH = '/api/v1/faq/update';
