/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ICreateFaqReqDto } from '../../models/i-create-faq-req-dto';
import { ICreateFaqResDto } from '../../models/i-create-faq-res-dto';

export interface FaqApiControllerCreate$Params {
      body: ICreateFaqReqDto
}

export function faqApiControllerCreate(http: HttpClient, rootUrl: string, params: FaqApiControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ICreateFaqResDto>> {
  const rb = new RequestBuilder(rootUrl, faqApiControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ICreateFaqResDto>;
    })
  );
}

faqApiControllerCreate.PATH = '/api/v1/faq/create';
