/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IFindFaqReqDto } from '../../models/i-find-faq-req-dto';
import { IFindFaqResDto } from '../../models/i-find-faq-res-dto';

export interface FaqApiControllerFind$Params {
      body: IFindFaqReqDto
}

export function faqApiControllerFind(http: HttpClient, rootUrl: string, params: FaqApiControllerFind$Params, context?: HttpContext): Observable<StrictHttpResponse<IFindFaqResDto>> {
  const rb = new RequestBuilder(rootUrl, faqApiControllerFind.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IFindFaqResDto>;
    })
  );
}

faqApiControllerFind.PATH = '/api/v1/faq/find';
