/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { ApiOrdersService } from './services/api-orders.service';
import { ApiTariffsService } from './services/api-tariffs.service';
import { ApiQuotesService } from './services/api-quotes.service';
import { ApiLocationsService } from './services/api-locations.service';
import { ApiTripsService } from './services/api-trips.service';
import { ApiFaqService } from './services/api-faq.service';
import { ApiReviewsService } from './services/api-reviews.service';
import { ApiFormsCallbackService } from './services/api-forms-callback.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    ApiOrdersService,
    ApiTariffsService,
    ApiQuotesService,
    ApiLocationsService,
    ApiTripsService,
    ApiFaqService,
    ApiReviewsService,
    ApiFormsCallbackService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
