/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ICallbackFormSchema } from './models/i-callback-form-schema';
export type { ICoordinatesSchema } from './models/i-coordinates-schema';
export type { ICreateCallbackFormReqDto } from './models/i-create-callback-form-req-dto';
export type { ICreateFaqReqDto } from './models/i-create-faq-req-dto';
export type { ICreateFaqResDto } from './models/i-create-faq-res-dto';
export type { ICreateOrderReqDto } from './models/i-create-order-req-dto';
export type { ICreateOrderResDto } from './models/i-create-order-res-dto';
export type { ICreateReviewReqDto } from './models/i-create-review-req-dto';
export type { ICreateReviewResDto } from './models/i-create-review-res-dto';
export type { ICreateTripReqDto } from './models/i-create-trip-req-dto';
export type { ICreateTripResDto } from './models/i-create-trip-res-dto';
export { IECallbackFormStatus } from './models/ie-callback-form-status';
export { IFaqSource } from './models/i-faq-source';
export type { IFindCallbackFormsResDto } from './models/i-find-callback-forms-res-dto';
export type { IFindFaqItemDto } from './models/i-find-faq-item-dto';
export type { IFindFaqReqDto } from './models/i-find-faq-req-dto';
export type { IFindFaqResDto } from './models/i-find-faq-res-dto';
export type { IFindLocationsItemDto } from './models/i-find-locations-item-dto';
export type { IFindLocationsResDto } from './models/i-find-locations-res-dto';
export type { IFindReviewsItemDto } from './models/i-find-reviews-item-dto';
export type { IFindReviewsReqDto } from './models/i-find-reviews-req-dto';
export type { IFindReviewsResDto } from './models/i-find-reviews-res-dto';
export type { IFindTariffsItemDto } from './models/i-find-tariffs-item-dto';
export type { IFindTariffsResDto } from './models/i-find-tariffs-res-dto';
export type { IFindTripsItemDto } from './models/i-find-trips-item-dto';
export type { IFindTripsReqDto } from './models/i-find-trips-req-dto';
export type { IFindTripsResDto } from './models/i-find-trips-res-dto';
export type { ILocationSchema } from './models/i-location-schema';
export type { ILocationSlugsSchema } from './models/i-location-slugs-schema';
export type { IPagedResponseDto } from './models/i-paged-response-dto';
export type { IPaginationMetaDto } from './models/i-pagination-meta-dto';
export type { IQuoteWithPricesDto } from './models/i-quote-with-prices-dto';
export type { IReviewReplySchema } from './models/i-review-reply-schema';
export type { IRouteSummaryDto } from './models/i-route-summary-dto';
export type { IRouteTripSchema } from './models/i-route-trip-schema';
export type { ITariffPriceItemDto } from './models/i-tariff-price-item-dto';
export type { ITariffSchema } from './models/i-tariff-schema';
export type { IUpdateFaqReqDto } from './models/i-update-faq-req-dto';
export type { IUpdateFaqResDto } from './models/i-update-faq-res-dto';
