/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ApiOrdersService } from './services/api-orders.service';
export { ApiTariffsService } from './services/api-tariffs.service';
export { ApiQuotesService } from './services/api-quotes.service';
export { ApiLocationsService } from './services/api-locations.service';
export { ApiTripsService } from './services/api-trips.service';
export { ApiFaqService } from './services/api-faq.service';
export { ApiReviewsService } from './services/api-reviews.service';
export { ApiFormsCallbackService } from './services/api-forms-callback.service';
