/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IFindCallbackFormsResDto } from '../../models/i-find-callback-forms-res-dto';

export interface FormsCallbackApiControllerFind$Params {
}

export function formsCallbackApiControllerFind(http: HttpClient, rootUrl: string, params?: FormsCallbackApiControllerFind$Params, context?: HttpContext): Observable<StrictHttpResponse<IFindCallbackFormsResDto>> {
  const rb = new RequestBuilder(rootUrl, formsCallbackApiControllerFind.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IFindCallbackFormsResDto>;
    })
  );
}

formsCallbackApiControllerFind.PATH = '/api/v1/callback-forms';
