/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IFindTariffsResDto } from '../../models/i-find-tariffs-res-dto';

export interface TariffsApiControllerFind$Params {
}

export function tariffsApiControllerFind(http: HttpClient, rootUrl: string, params?: TariffsApiControllerFind$Params, context?: HttpContext): Observable<StrictHttpResponse<IFindTariffsResDto>> {
  const rb = new RequestBuilder(rootUrl, tariffsApiControllerFind.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IFindTariffsResDto>;
    })
  );
}

tariffsApiControllerFind.PATH = '/api/v1/tariffs/find';
