/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IFindTripsReqDto } from '../../models/i-find-trips-req-dto';
import { IFindTripsResDto } from '../../models/i-find-trips-res-dto';

export interface TripsApiControllerFind$Params {
      body: IFindTripsReqDto
}

export function tripsApiControllerFind(http: HttpClient, rootUrl: string, params: TripsApiControllerFind$Params, context?: HttpContext): Observable<StrictHttpResponse<IFindTripsResDto>> {
  const rb = new RequestBuilder(rootUrl, tripsApiControllerFind.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IFindTripsResDto>;
    })
  );
}

tripsApiControllerFind.PATH = '/api/v1/trips/find';
