/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IFindReviewsReqDto } from '../../models/i-find-reviews-req-dto';
import { IFindReviewsResDto } from '../../models/i-find-reviews-res-dto';

export interface ReviewsApiControllerFind$Params {
      body: IFindReviewsReqDto
}

export function reviewsApiControllerFind(http: HttpClient, rootUrl: string, params: ReviewsApiControllerFind$Params, context?: HttpContext): Observable<StrictHttpResponse<IFindReviewsResDto>> {
  const rb = new RequestBuilder(rootUrl, reviewsApiControllerFind.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IFindReviewsResDto>;
    })
  );
}

reviewsApiControllerFind.PATH = '/api/v1/reviews/find';
