/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ICreateReviewReqDto } from '../../models/i-create-review-req-dto';
import { ICreateReviewResDto } from '../../models/i-create-review-res-dto';

export interface ReviewsApiControllerCreate$Params {
      body: ICreateReviewReqDto
}

export function reviewsApiControllerCreate(http: HttpClient, rootUrl: string, params: ReviewsApiControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ICreateReviewResDto>> {
  const rb = new RequestBuilder(rootUrl, reviewsApiControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ICreateReviewResDto>;
    })
  );
}

reviewsApiControllerCreate.PATH = '/api/v1/reviews/create';
