/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ICreateOrderResDto } from '../models/i-create-order-res-dto';
import { orderControllerCreateOrder } from '../fn/orders/order-controller-create-order';
import { OrderControllerCreateOrder$Params } from '../fn/orders/order-controller-create-order';

@Injectable({ providedIn: 'root' })
export class ApiOrdersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `orderControllerCreateOrder()` */
  static readonly OrderControllerCreateOrderPath = '/api/v1/order';

  /**
   * Создание новой заявки на трансфер.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderControllerCreateOrder()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  orderControllerCreateOrder$Response(params: OrderControllerCreateOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<ICreateOrderResDto>> {
    return orderControllerCreateOrder(this.http, this.rootUrl, params, context);
  }

  /**
   * Создание новой заявки на трансфер.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderControllerCreateOrder$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  orderControllerCreateOrder(params: OrderControllerCreateOrder$Params, context?: HttpContext): Observable<ICreateOrderResDto> {
    return this.orderControllerCreateOrder$Response(params, context).pipe(
      map((r: StrictHttpResponse<ICreateOrderResDto>): ICreateOrderResDto => r.body)
    );
  }

}
