/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ICreateTripResDto } from '../models/i-create-trip-res-dto';
import { IFindTripsResDto } from '../models/i-find-trips-res-dto';
import { tripsApiControllerCreate } from '../fn/trips/trips-api-controller-create';
import { TripsApiControllerCreate$Params } from '../fn/trips/trips-api-controller-create';
import { tripsApiControllerFind } from '../fn/trips/trips-api-controller-find';
import { TripsApiControllerFind$Params } from '../fn/trips/trips-api-controller-find';

@Injectable({ providedIn: 'root' })
export class ApiTripsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `tripsApiControllerCreate()` */
  static readonly TripsApiControllerCreatePath = '/api/v1/trips/create';

  /**
   * Создание новой поездки.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `tripsApiControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  tripsApiControllerCreate$Response(params: TripsApiControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ICreateTripResDto>> {
    return tripsApiControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Создание новой поездки.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `tripsApiControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  tripsApiControllerCreate(params: TripsApiControllerCreate$Params, context?: HttpContext): Observable<ICreateTripResDto> {
    return this.tripsApiControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<ICreateTripResDto>): ICreateTripResDto => r.body)
    );
  }

  /** Path part for operation `tripsApiControllerFind()` */
  static readonly TripsApiControllerFindPath = '/api/v1/trips/find';

  /**
   * Получение списка поездок.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `tripsApiControllerFind()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  tripsApiControllerFind$Response(params: TripsApiControllerFind$Params, context?: HttpContext): Observable<StrictHttpResponse<IFindTripsResDto>> {
    return tripsApiControllerFind(this.http, this.rootUrl, params, context);
  }

  /**
   * Получение списка поездок.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `tripsApiControllerFind$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  tripsApiControllerFind(params: TripsApiControllerFind$Params, context?: HttpContext): Observable<IFindTripsResDto> {
    return this.tripsApiControllerFind$Response(params, context).pipe(
      map((r: StrictHttpResponse<IFindTripsResDto>): IFindTripsResDto => r.body)
    );
  }

}
