/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ICreateReviewResDto } from '../models/i-create-review-res-dto';
import { IFindReviewsResDto } from '../models/i-find-reviews-res-dto';
import { reviewsApiControllerCreate } from '../fn/reviews/reviews-api-controller-create';
import { ReviewsApiControllerCreate$Params } from '../fn/reviews/reviews-api-controller-create';
import { reviewsApiControllerFind } from '../fn/reviews/reviews-api-controller-find';
import { ReviewsApiControllerFind$Params } from '../fn/reviews/reviews-api-controller-find';

@Injectable({ providedIn: 'root' })
export class ApiReviewsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `reviewsApiControllerCreate()` */
  static readonly ReviewsApiControllerCreatePath = '/api/v1/reviews/create';

  /**
   * Создание нового отзыва.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reviewsApiControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reviewsApiControllerCreate$Response(params: ReviewsApiControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ICreateReviewResDto>> {
    return reviewsApiControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Создание нового отзыва.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reviewsApiControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reviewsApiControllerCreate(params: ReviewsApiControllerCreate$Params, context?: HttpContext): Observable<ICreateReviewResDto> {
    return this.reviewsApiControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<ICreateReviewResDto>): ICreateReviewResDto => r.body)
    );
  }

  /** Path part for operation `reviewsApiControllerFind()` */
  static readonly ReviewsApiControllerFindPath = '/api/v1/reviews/find';

  /**
   * Поиск отзывов по фильтрам.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reviewsApiControllerFind()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reviewsApiControllerFind$Response(params: ReviewsApiControllerFind$Params, context?: HttpContext): Observable<StrictHttpResponse<IFindReviewsResDto>> {
    return reviewsApiControllerFind(this.http, this.rootUrl, params, context);
  }

  /**
   * Поиск отзывов по фильтрам.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reviewsApiControllerFind$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reviewsApiControllerFind(params: ReviewsApiControllerFind$Params, context?: HttpContext): Observable<IFindReviewsResDto> {
    return this.reviewsApiControllerFind$Response(params, context).pipe(
      map((r: StrictHttpResponse<IFindReviewsResDto>): IFindReviewsResDto => r.body)
    );
  }

}
