/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ICallbackFormSchema } from '../models/i-callback-form-schema';
import { IFindCallbackFormsResDto } from '../models/i-find-callback-forms-res-dto';
import { formsCallbackApiControllerCreate } from '../fn/forms-callback/forms-callback-api-controller-create';
import { FormsCallbackApiControllerCreate$Params } from '../fn/forms-callback/forms-callback-api-controller-create';
import { formsCallbackApiControllerFind } from '../fn/forms-callback/forms-callback-api-controller-find';
import { FormsCallbackApiControllerFind$Params } from '../fn/forms-callback/forms-callback-api-controller-find';

@Injectable({ providedIn: 'root' })
export class ApiFormsCallbackService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `formsCallbackApiControllerFind()` */
  static readonly FormsCallbackApiControllerFindPath = '/api/v1/callback-forms';

  /**
   * Получить список заявок обратной связи.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `formsCallbackApiControllerFind()` instead.
   *
   * This method doesn't expect any request body.
   */
  formsCallbackApiControllerFind$Response(params?: FormsCallbackApiControllerFind$Params, context?: HttpContext): Observable<StrictHttpResponse<IFindCallbackFormsResDto>> {
    return formsCallbackApiControllerFind(this.http, this.rootUrl, params, context);
  }

  /**
   * Получить список заявок обратной связи.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `formsCallbackApiControllerFind$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  formsCallbackApiControllerFind(params?: FormsCallbackApiControllerFind$Params, context?: HttpContext): Observable<IFindCallbackFormsResDto> {
    return this.formsCallbackApiControllerFind$Response(params, context).pipe(
      map((r: StrictHttpResponse<IFindCallbackFormsResDto>): IFindCallbackFormsResDto => r.body)
    );
  }

  /** Path part for operation `formsCallbackApiControllerCreate()` */
  static readonly FormsCallbackApiControllerCreatePath = '/api/v1/callback-forms';

  /**
   * Создать новую форму обратной связи.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `formsCallbackApiControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  formsCallbackApiControllerCreate$Response(params: FormsCallbackApiControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ICallbackFormSchema>> {
    return formsCallbackApiControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Создать новую форму обратной связи.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `formsCallbackApiControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  formsCallbackApiControllerCreate(params: FormsCallbackApiControllerCreate$Params, context?: HttpContext): Observable<ICallbackFormSchema> {
    return this.formsCallbackApiControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<ICallbackFormSchema>): ICallbackFormSchema => r.body)
    );
  }

}
