/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { IFindLocationsResDto } from '../models/i-find-locations-res-dto';
import { locationsApiControllerFind } from '../fn/locations/locations-api-controller-find';
import { LocationsApiControllerFind$Params } from '../fn/locations/locations-api-controller-find';

@Injectable({ providedIn: 'root' })
export class ApiLocationsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `locationsApiControllerFind()` */
  static readonly LocationsApiControllerFindPath = '/api/v1/locations/find';

  /**
   * Автокомплит по названию локации.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `locationsApiControllerFind()` instead.
   *
   * This method doesn't expect any request body.
   */
  locationsApiControllerFind$Response(params?: LocationsApiControllerFind$Params, context?: HttpContext): Observable<StrictHttpResponse<IFindLocationsResDto>> {
    return locationsApiControllerFind(this.http, this.rootUrl, params, context);
  }

  /**
   * Автокомплит по названию локации.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `locationsApiControllerFind$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  locationsApiControllerFind(params?: LocationsApiControllerFind$Params, context?: HttpContext): Observable<IFindLocationsResDto> {
    return this.locationsApiControllerFind$Response(params, context).pipe(
      map((r: StrictHttpResponse<IFindLocationsResDto>): IFindLocationsResDto => r.body)
    );
  }

}
