/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { IFindTariffsResDto } from '../models/i-find-tariffs-res-dto';
import { tariffsApiControllerFind } from '../fn/tariffs/tariffs-api-controller-find';
import { TariffsApiControllerFind$Params } from '../fn/tariffs/tariffs-api-controller-find';

@Injectable({ providedIn: 'root' })
export class ApiTariffsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `tariffsApiControllerFind()` */
  static readonly TariffsApiControllerFindPath = '/api/v1/tariffs/find';

  /**
   * Получение списка всех тарифов.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `tariffsApiControllerFind()` instead.
   *
   * This method doesn't expect any request body.
   */
  tariffsApiControllerFind$Response(params?: TariffsApiControllerFind$Params, context?: HttpContext): Observable<StrictHttpResponse<IFindTariffsResDto>> {
    return tariffsApiControllerFind(this.http, this.rootUrl, params, context);
  }

  /**
   * Получение списка всех тарифов.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `tariffsApiControllerFind$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  tariffsApiControllerFind(params?: TariffsApiControllerFind$Params, context?: HttpContext): Observable<IFindTariffsResDto> {
    return this.tariffsApiControllerFind$Response(params, context).pipe(
      map((r: StrictHttpResponse<IFindTariffsResDto>): IFindTariffsResDto => r.body)
    );
  }

}
