/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { quotesControllerRoute } from '../fn/quotes/quotes-controller-route';
import { QuotesControllerRoute$Params } from '../fn/quotes/quotes-controller-route';
import { IQuoteWithPricesDto } from '../models/i-quote-with-prices-dto';

@Injectable({ providedIn: 'root' })
export class ApiQuotesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `quotesControllerRoute()` */
  static readonly QuotesControllerRoutePath = '/api/v1/quotes/route';

  /**
   * Получить маршрут и цены по тарифам.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `quotesControllerRoute()` instead.
   *
   * This method doesn't expect any request body.
   */
  quotesControllerRoute$Response(params: QuotesControllerRoute$Params, context?: HttpContext): Observable<StrictHttpResponse<IQuoteWithPricesDto>> {
    return quotesControllerRoute(this.http, this.rootUrl, params, context);
  }

  /**
   * Получить маршрут и цены по тарифам.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `quotesControllerRoute$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  quotesControllerRoute(params: QuotesControllerRoute$Params, context?: HttpContext): Observable<IQuoteWithPricesDto> {
    return this.quotesControllerRoute$Response(params, context).pipe(
      map((r: StrictHttpResponse<IQuoteWithPricesDto>): IQuoteWithPricesDto => r.body)
    );
  }

}
