/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ICreateFaqResDto } from '../models/i-create-faq-res-dto';
import { faqApiControllerCreate } from '../fn/faq/faq-api-controller-create';
import { FaqApiControllerCreate$Params } from '../fn/faq/faq-api-controller-create';
import { faqApiControllerFind } from '../fn/faq/faq-api-controller-find';
import { FaqApiControllerFind$Params } from '../fn/faq/faq-api-controller-find';
import { faqApiControllerUpdate } from '../fn/faq/faq-api-controller-update';
import { FaqApiControllerUpdate$Params } from '../fn/faq/faq-api-controller-update';
import { IFindFaqResDto } from '../models/i-find-faq-res-dto';
import { IUpdateFaqResDto } from '../models/i-update-faq-res-dto';

@Injectable({ providedIn: 'root' })
export class ApiFaqService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `faqApiControllerCreate()` */
  static readonly FaqApiControllerCreatePath = '/api/v1/faq/create';

  /**
   * Создать FAQ-элемент.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `faqApiControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  faqApiControllerCreate$Response(params: FaqApiControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ICreateFaqResDto>> {
    return faqApiControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * Создать FAQ-элемент.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `faqApiControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  faqApiControllerCreate(params: FaqApiControllerCreate$Params, context?: HttpContext): Observable<ICreateFaqResDto> {
    return this.faqApiControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<ICreateFaqResDto>): ICreateFaqResDto => r.body)
    );
  }

  /** Path part for operation `faqApiControllerFind()` */
  static readonly FaqApiControllerFindPath = '/api/v1/faq/find';

  /**
   * Найти FAQ-элементы (фильтры, поиск, пагинация).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `faqApiControllerFind()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  faqApiControllerFind$Response(params: FaqApiControllerFind$Params, context?: HttpContext): Observable<StrictHttpResponse<IFindFaqResDto>> {
    return faqApiControllerFind(this.http, this.rootUrl, params, context);
  }

  /**
   * Найти FAQ-элементы (фильтры, поиск, пагинация).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `faqApiControllerFind$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  faqApiControllerFind(params: FaqApiControllerFind$Params, context?: HttpContext): Observable<IFindFaqResDto> {
    return this.faqApiControllerFind$Response(params, context).pipe(
      map((r: StrictHttpResponse<IFindFaqResDto>): IFindFaqResDto => r.body)
    );
  }

  /** Path part for operation `faqApiControllerUpdate()` */
  static readonly FaqApiControllerUpdatePath = '/api/v1/faq/update';

  /**
   * Обновить FAQ-элемент по id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `faqApiControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  faqApiControllerUpdate$Response(params: FaqApiControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<IUpdateFaqResDto>> {
    return faqApiControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * Обновить FAQ-элемент по id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `faqApiControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  faqApiControllerUpdate(params: FaqApiControllerUpdate$Params, context?: HttpContext): Observable<IUpdateFaqResDto> {
    return this.faqApiControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<IUpdateFaqResDto>): IUpdateFaqResDto => r.body)
    );
  }

}
